# Generated by Django 4.2 on 2025-05-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_color',
            field=models.CharField(default='#cccccc', max_length=7),
        ),
    ]
