# Generated by Django 4.2 on 2025-05-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_category'),
        ('accounts', '0002_alter_user_profile_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, related_name='users_favorited', to='books.category'),
        ),
    ]
