# Generated by Django 4.2 on 2025-05-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_book_color_book_cover_book_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cid_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
